Update ABOUT.md
exercism/lfe pull request #248
Opened 2024-06-02 13:34 UTC by Santiago00lp

Update doc with benefits of LFE

2024-06-02 18:39 UTC, BNAndras commented on docs/ABOUT.md
> +**Lisp Flavoured Erlang** (AKA LFE) is a lisp syntax **front-end** to the **Erlang compiler**.
```suggestion
**Lisp Flavoured Erlang** (AKA LFE) is a Lisp syntax **front-end** to the **Erlang compiler**. 
```

2024-06-02 18:39 UTC, BNAndras commented on docs/ABOUT.md
> +**Key Benefits:**
We list out key features for LFE at https://github.com/exercism/lfe/blob/13ec9033ee17a056d7f9c2acb6e8fc7af813fa2b/config.json#L498. This appears on the track's about page at https://exercism.org/tracks/lfe/about underneath the contents of this file. There we shouldn't repeat that information here.

2024-06-02 18:39 UTC, BNAndras commented on docs/ABOUT.md
>  Code produced with it is compatible with "normal" Erlang code.
I think we should remove "normal" here since it's unclear what this means.

2024-06-02 18:39 UTC, BNAndras commented on docs/ABOUT.md
>  LFE is a (proper) Lisp based on the features and limitations of the Erlang VM.
This sentence is a bit vague. What is proper? What are the features and limitations of the Erlang VM? This doesn't add any information to the last two sentences so perhaps it's best to remove it.

2024-06-02 18:39 UTC, BNAndras commented on docs/ABOUT.md
>  LFE has many origins, depending upon whether you're looking at Lisp, Erlang, or LFE-proper.
This sentence is a bit vague. Perhaps we should play up that LFE predates Elixir and the creator, Robert Virding, was a co-creator of Erlang itself. We could highlight that Common Lisp is a strong influence on LFE.

2024-06-02 18:39 UTC, BNAndras commented on docs/ABOUT.md
>  The LFE community of contributors embraces all of these and more.
This sentence doesn't really describe how the origins are embraced so this sentence can be dropped entirely for the sake of brevity.

2024-06-04 03:34 UTC, Santiago00lp commented
Thanks for the feedback, here is a new version.

2024-06-21 00:05 UTC, kotp requested changes
Line ending and typo-graphical error.

2024-06-21 00:05 UTC, kotp commented on docs/ABOUT.md
> +**Lisp Flavoured Erlang** (AKA LFE) cmbine the robustness and concurrency of Erlang with the flexibility and power of a Lisp syntax.
```suggestion
**Lisp Flavoured Erlang** (AKA LFE) combine the robustness and concurrency of Erlang with the flexibility and power of a Lisp syntax.
```

2024-06-21 00:05 UTC, kotp commented on docs/ABOUT.md
> +LFE predates Elixir and was created by Robert Virding, one of the original developers of Erlang. With strong influences from Common Lisp, LFE is built on a foundation of decades of programming langua
```suggestion
LFE predates Elixir and was created by Robert Virding, one of the original developers of Erlang. With strong influences from Common Lisp, LFE is built on a foundation of decades of programming language development.

```

2024-06-21 01:37 UTC, BNAndras commented
Looks like the CI is flaking again. I’ll take a look at binary this weekend.

2024-06-24 06:26 UTC, BNAndras commented
Once merged, #254 should fix the CI issue.

2024-06-24 23:25 UTC, kotp approved these changes

2024-06-24 23:27 UTC, merged