Add knapsack exercise
exercism/lfe pull request #264
Opened 2024-07-13 03:36 UTC by kahgoh

This is one of the [48in24](https://forum.exercism.org/t/48in24-exercise-08-13-knapsack/12054) exercises.

2024-07-13 04:06 UTC, BNAndras requested changes

2024-07-13 04:06 UTC, BNAndras commented on exercises/practice/knapsack/test/knapsack-tests.lfe
`(knapsack:maximum-value ...)` should be indented at the same level as the expected value. Otherwise, it can be hard to spot the expected values when scanning the test suite.

2024-07-13 04:06 UTC, BNAndras commented on exercises/practice/knapsack/test/knapsack-tests.lfe
> +  (is-equal 0 (knapsack:maximum-value [] 100)))
```suggestion
  (is-equal 0 (knapsack:maximum-value '() 100)))
```
To avoid confusion, we should be consistent on how we represent lists.

2024-07-13 04:06 UTC, BNAndras commented on exercises/practice/knapsack/src/knapsack.lfe
> +            (new-item 2)))
(new-item 2) should be dedented so it's flush with (maximum-value 2)

2024-07-13 14:09 UTC, kahgoh commented on exercises/practice/knapsack/src/knapsack.lfe
The down side with removing the stubs is that it might not be obvious in which order the `new-item` arguments are. To resolve this, I've just learnt how to "share" the `item` record between the stub and the test (using an include), allowing me to remove the `new-item` function altogether.

2024-07-13 14:12 UTC, kahgoh commented on exercises/practice/binary/src/example.lfe
That was definitely unintended! I'll remove the file.

2024-07-13 21:30 UTC, BNAndras commented on exercises/practice/knapsack/src/knapsack.lfe
The instructions indicate the order. If we want to provide the record definition for clarity, that's fine. However, it should be done in the test suite before the tests are defined so all the information is in one place.

2024-07-14 05:14 UTC, BNAndras commented on exercises/practice/knapsack/src/knapsack.lfe
Now that I look at this closer, this isn't ideal since although you could manually access the item weight and value `(element 2 item)` and `(element 3 item)`, students probably are going to define the record again locally. The best way forward is your previous include for the `item` record. Are the additional editor files editable? We should probably put a comment in there that students don't need to edit code there.

I don't recall LFE having documentation for records but we could use a short instructions.append.md here. I think a sentence describing that we're using records here and an example or two showing how to access a record field.

2024-07-14 05:24 UTC, kotp commented on exercises/practice/knapsack/test/knapsack-tests.lfe
> +              750)))
```suggestion
              750)))
              
```

To make the line endings consistent for every line, including the last one.

2024-07-16 13:12 UTC, kahgoh commented on exercises/practice/knapsack/src/knapsack.lfe
>  Are the additional editor files editable? We should probably put a comment in there that students don't need to edit code there.

Yup, files in the `editor` key are read only. This is mentioned in the [docs](https://exercism.org/docs/building/tracks/config-json) and we have also used this in the [Wizards and Warriors 2 concept exercise on the Java track](https://github.com/exercism/java/blob/main/exercises/concept/wizards-and-warriors-2/.meta/config.json). 

> I don't recall LFE having documentation for records but we could use a short instructions.append.md here. I think a sentence describing that we're using records here and an example or two showing how to access a record field.

I'm happy to write something in an instruction.append.md, but want to double check something first. I actually first learnt about the records from their docs. Admittedly, it isn't obvious how to get to it purely by navigating from their main page, but from their docs, there is section in the [user guide](https://github.com/lfe/lfe/blob/15a70dffa0f3055ef06ecca0009cbc09c96847b5/doc/user_guide.txt#L694) and their [reference book](https://lfe.gitbooks.io/reference-guide/content/16.html). Given this, I just wanted to check if you still think we should have an instruction.append.md? 

By the way, I notice their [reference guide](https://lfe.gitbooks.io/reference-guide/content/) isn't in the [learning resources](https://github.com/exercism/lfe/blob/main/docs/LEARNING.md).  Would you be happy for me to add it?

2024-07-17 01:05 UTC, BNAndras commented on exercises/practice/knapsack/src/knapsack.lfe
My understanding is the Gitbooks site for LFE hasn't been maintained actively for several years. They had some issues taking that reference book site down so it's abandoned but still shows up in Google Search. We probably should still do the instructions.append since we can control its content and provide what's needed.

2024-07-17 14:29 UTC, BNAndras approved these changes

2024-07-17 14:29 UTC, merged